name: w3b publish

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - name: Copy README
        run: cp ./README.md ./apps/w3b/README.md
      - run: pnpm --filter @guchii/w3b test
      - run: pnpm --filter @guchii/w3b semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-demo:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          pnpm --filter web3-test build
          mkdir -p dist
          cp -r ./apps/demo/dist/* dist/
          touch dist/.nojekyll
        name: Build demo
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}